name: new_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  # example:
  fonts:
    - family: EpundaSlab
      fonts:
        - asset: assets/fonts/EpundaSlab-Regular.ttf
        - asset: assets/fonts/EpundaSlab-Italic.ttf
          style: italic
        - asset: assets/fonts/EpundaSlab-Bold.ttf
          weight: 800
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf
        

